---
- name: Install required system packages for Debian
  apt:
    name: 
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
    state: present
  when: ansible_os_family == 'Debian'

- name: Add Docker GPG key for Debian
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  when: ansible_os_family == 'Debian'

- name: Add Docker repository for Debian
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    state: present
  when: ansible_os_family == 'Debian'

- name: Update apt and install docker-ce for Debian
  apt:
    update_cache: yes
    name: docker-ce
    state: present
  when: ansible_os_family == 'Debian'

- name: Install required system packages for RHEL/CentOS
  yum:
    name:
      - yum-utils
      - device-mapper-persistent-data
      - lvm2
    state: present
  when: ansible_os_family == 'RedHat'

- name: Add Docker repository for RHEL/CentOS
  command: >
    yum-config-manager --add-repo
    https://download.docker.com/linux/centos/docker-ce.repo
  when: ansible_os_family == 'RedHat'

- name: Install docker-ce for RHEL/CentOS
  yum:
    name: docker-ce
    state: present
  when: ansible_os_family == 'RedHat'

- name: Start and enable Docker service
  service:
    name: docker
    state: started
    enabled: yes

- name: Install required system packages for Debian
  apt:
    name: 
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
    state: present
  when: ansible_os_family == 'Debian'

- name: Add Docker GPG key for Debian
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  when: ansible_os_family == 'Debian'

- name: Add Docker repository for Debian
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    state: present
  when: ansible_os_family == 'Debian'

- name: Update apt and install docker-ce for Debian
  apt:
    update_cache: yes
    name: docker-ce
    state: present
  when: ansible_os_family == 'Debian'

- name: Install required system packages for RHEL/CentOS
  yum:
    name:
      - yum-utils
      - device-mapper-persistent-data
      - lvm2
    state: present
  when: ansible_os_family == 'RedHat'

- name: Add Docker repository for RHEL/CentOS
  command: >
    yum-config-manager --add-repo
    https://download.docker.com/linux/centos/docker-ce.repo
  when: ansible_os_family == 'RedHat'

- name: Install docker-ce for RHEL/CentOS
  yum:
    name: docker-ce
    state: present
  when: ansible_os_family == 'RedHat'

- name: Start and enable Docker service
  service:
    name: dockerId
    state: started
    enabled: yes 
